"""
AI Failure Prediction Service
==============================
FastAPI + scikit-learn Isolation Forest
Polls Prometheus metrics → detects anomalies → publishes alerts

Endpoints:
  GET  /health          — liveness probe
  GET  /predict         — latest anomaly score for all services
  POST /predict/{svc}   — on-demand prediction for a service
  GET  /metrics         — Prometheus metrics (scraped by prometheus.yml)
  GET  /history         — last N anomaly events
  POST /train           — retrain model on latest data
  GET  /docs            — Swagger UI (auto-generated by FastAPI)
"""

import asyncio
import logging
import os
import time
from collections import deque
from datetime import datetime, timezone
from typing import Optional

import httpx
import numpy as np
from fastapi import FastAPI, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from prometheus_client import (
    Counter, Gauge, Histogram,
    generate_latest, CONTENT_TYPE_LATEST
)
from pydantic import BaseModel
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
from starlette.responses import Response

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s — %(message)s",
)
log = logging.getLogger("ai-predictor")

# ── Config (from environment / docker-compose) ────────────────────────────────
PROMETHEUS_URL      = os.getenv("PROMETHEUS_URL",        "http://localhost:9090")
ORDER_SERVICE_URL   = os.getenv("ORDER_SERVICE_URL",     "http://localhost:8081")
HEALING_SERVICE_URL = os.getenv("HEALING_SERVICE_URL",   "http://localhost:8082")
ANOMALY_THRESHOLD   = float(os.getenv("ANOMALY_THRESHOLD", "0.75"))
POLL_INTERVAL       = int(os.getenv("POLL_INTERVAL_SECONDS", "10"))
TRAINING_WINDOW     = int(os.getenv("TRAINING_WINDOW",   "100"))  # data points for training
HISTORY_SIZE        = int(os.getenv("HISTORY_SIZE",       "200"))  # events kept in memory
OLLAMA_URL          = os.getenv("OLLAMA_URL",             "http://localhost:11434")
OLLAMA_MODEL        = os.getenv("OLLAMA_MODEL",           "llama3")

# ── Prometheus custom metrics (exported at /metrics) ──────────────────────────
prom_anomaly_score = Gauge(
    "aipredictor_anomaly_score",
    "Current anomaly score (0–1) per service",
    ["service"]
)
prom_anomaly_total = Counter(
    "aipredictor_anomalies_total",
    "Total anomalies detected above threshold",
    ["service"]
)
prom_prediction_latency = Histogram(
    "aipredictor_prediction_duration_seconds",
    "Time to run one prediction cycle",
)
prom_training_total = Counter(
    "aipredictor_training_total",
    "Total model retrains",
)

# ── In-memory state ───────────────────────────────────────────────────────────
class ServiceState:
    """Holds model, scaler, rolling buffer, and last prediction for one service."""

    def __init__(self, name: str):
        self.name        = name
        self.model       = IsolationForest(
            n_estimators=100,
            contamination=0.05,   # expect ~5% anomalous samples
            random_state=42,
            n_jobs=-1,
        )
        self.scaler      = StandardScaler()
        self.buffer: deque = deque(maxlen=TRAINING_WINDOW)
        self.trained     = False
        self.last_score  = 0.0
        self.last_raw    = {}
        self.last_seen   = None

    def add_sample(self, features: list[float]):
        self.buffer.append(features)

    def train(self):
        if len(self.buffer) < 20:
            log.info("[%s] Not enough data to train (%d samples)", self.name, len(self.buffer))
            return False
        X = np.array(list(self.buffer))
        X_scaled = self.scaler.fit_transform(X)
        self.model.fit(X_scaled)
        self.trained = True
        prom_training_total.inc()
        log.info("[%s] Model trained on %d samples", self.name, len(self.buffer))
        return True

    def predict(self, features: list[float]) -> float:
        """Returns anomaly score 0.0 (normal) → 1.0 (highly anomalous)."""
        if not self.trained:
            return 0.0
        x = np.array(features).reshape(1, -1)
        x_scaled = self.scaler.transform(x)
        # decision_function: negative = anomaly, positive = normal
        raw_score = self.model.decision_function(x_scaled)[0]
        # Normalise to [0, 1]; more negative = higher anomaly score
        score = float(np.clip(0.5 - raw_score, 0.0, 1.0))
        return score


# Monitored services (add more here as you build them)
SERVICES = {
    "order-service": ServiceState("order-service"),
}

# History ring buffer
history: deque = deque(maxlen=HISTORY_SIZE)

# ── Pydantic models ───────────────────────────────────────────────────────────
class PredictionResult(BaseModel):
    service:       str
    anomaly_score: float
    is_anomaly:    bool
    threshold:     float
    features:      dict
    trained:       bool
    timestamp:     str
    recommendation: Optional[str] = None
    llm_analysis:  Optional[str] = None

class TrainResponse(BaseModel):
    service: str
    success: bool
    samples: int
    message: str

class HealthResponse(BaseModel):
    status:   str
    services: dict
    uptime_s: int

# ── FastAPI app ───────────────────────────────────────────────────────────────
app = FastAPI(
    title="AI Failure Predictor",
    description="Isolation Forest anomaly detection for microservice health",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

START_TIME = time.time()

# ── Prometheus helpers ────────────────────────────────────────────────────────
async def query_prometheus(client: httpx.AsyncClient, promql: str) -> Optional[float]:
    """Run an instant PromQL query and return the scalar value."""
    try:
        resp = await client.get(
            f"{PROMETHEUS_URL}/api/v1/query",
            params={"query": promql},
            timeout=5.0,
        )
        data = resp.json()
        results = data.get("data", {}).get("result", [])
        if results:
            return float(results[0]["value"][1])
        return None
    except Exception as exc:
        log.warning("Prometheus query failed [%s]: %s", promql, exc)
        return None


async def fetch_metrics_for_service(
    client: httpx.AsyncClient,
    service: str,
) -> Optional[dict]:
    """
    Pull the features we feed into Isolation Forest.

    Features (all from Spring Boot Actuator via Prometheus):
      1. error_rate_pct   — % of requests returning 5xx in the last 1 min
      2. latency_p95_ms   — 95th-percentile response time in ms
      3. latency_p50_ms   — 50th-percentile response time
      4. req_rate_per_sec — requests per second (volume signal)
      5. jvm_heap_used_mb — JVM heap usage (memory pressure signal)
      6. gc_pause_rate    — GC pause events per second
    """
    instance = f"{service}:8080" if "service" in service else service

    # 5xx error rate
    error_rate = await query_prometheus(
        client,
        f'rate(http_server_requests_seconds_count{{instance="{instance}",status=~"5.."}}[1m])'
        f' / rate(http_server_requests_seconds_count{{instance="{instance}"}}[1m]) * 100'
    )

    # p95 latency
    latency_p95 = await query_prometheus(
        client,
        f'histogram_quantile(0.95, rate(http_server_requests_seconds_bucket{{instance="{instance}"}}[1m])) * 1000'
    )

    # p50 latency
    latency_p50 = await query_prometheus(
        client,
        f'histogram_quantile(0.50, rate(http_server_requests_seconds_bucket{{instance="{instance}"}}[1m])) * 1000'
    )

    # Request rate
    req_rate = await query_prometheus(
        client,
        f'rate(http_server_requests_seconds_count{{instance="{instance}"}}[1m])'
    )

    # JVM heap
    heap_mb = await query_prometheus(
        client,
        f'jvm_memory_used_bytes{{instance="{instance}",area="heap"}} / 1048576'
    )

    # GC pause rate
    gc_rate = await query_prometheus(
        client,
        f'rate(jvm_gc_pause_seconds_count{{instance="{instance}"}}[1m])'
    )

    # If Prometheus has no data yet (service just started), use fallback from Actuator
    if error_rate is None:
        try:
            actuator_resp = await client.get(
                f"{ORDER_SERVICE_URL}/actuator/metrics/http.server.requests",
                timeout=3.0,
            )
            # Rough extraction — replace with proper parsing in production
            error_rate = 2.0
        except Exception:
            error_rate = 0.0

    raw = {
        "error_rate_pct":    round(error_rate  or 0.0, 3),
        "latency_p95_ms":    round(latency_p95 or 120.0, 2),
        "latency_p50_ms":    round(latency_p50 or 80.0, 2),
        "req_rate_per_sec":  round(req_rate    or 0.0, 3),
        "jvm_heap_used_mb":  round(heap_mb     or 0.0, 1),
        "gc_pause_rate":     round(gc_rate     or 0.0, 4),
    }
    return raw


def raw_to_features(raw: dict) -> list[float]:
    return [
        raw["error_rate_pct"],
        raw["latency_p95_ms"],
        raw["latency_p50_ms"],
        raw["req_rate_per_sec"],
        raw["jvm_heap_used_mb"],
        raw["gc_pause_rate"],
    ]


def recommendation(score: float, raw: dict) -> str:
    if score < 0.45:
        return "Service healthy — no action required."
    if score < 0.75:
        return (
            f"Elevated anomaly score ({score:.2f}). "
            f"Error rate {raw['error_rate_pct']:.1f}%, latency p95 {raw['latency_p95_ms']:.0f}ms. "
            "Continue monitoring."
        )
    return (
        f"CRITICAL: Anomaly score {score:.2f} exceeds threshold {ANOMALY_THRESHOLD}. "
        f"Error rate {raw['error_rate_pct']:.1f}%, latency p95 {raw['latency_p95_ms']:.0f}ms. "
        "Triggering circuit breaker."
    )


async def llm_explain(raw: dict, score: float) -> Optional[str]:
    """Ask Ollama Llama 3 to explain the anomaly in plain English."""
    prompt = (
        "You are an SRE assistant. Analyze these microservice metrics and give a "
        "one-sentence root cause hypothesis in plain English (no markdown, no bullet points):\n\n"
        f"Error rate: {raw['error_rate_pct']:.1f}%\n"
        f"Latency p95: {raw['latency_p95_ms']:.0f}ms\n"
        f"Latency p50: {raw['latency_p50_ms']:.0f}ms\n"
        f"Request rate: {raw['req_rate_per_sec']:.2f} req/s\n"
        f"JVM heap: {raw['jvm_heap_used_mb']:.0f} MB\n"
        f"Anomaly score: {score:.2f}/1.00\n"
    )
    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            resp = await client.post(
                f"{OLLAMA_URL}/api/generate",
                json={"model": OLLAMA_MODEL, "prompt": prompt, "stream": False},
            )
            return resp.json().get("response", "").strip()
    except Exception as exc:
        log.debug("Ollama unavailable: %s", exc)
        return None


# ── Background polling loop ───────────────────────────────────────────────────
async def poll_loop():
    """Continuously polls Prometheus, updates models, and publishes anomaly scores."""
    log.info("Poll loop started — interval %ds, threshold %.2f", POLL_INTERVAL, ANOMALY_THRESHOLD)

    # Warm-up: collect baseline data for TRAINING_WINDOW / 5 polls before first train
    warmup_target = max(20, TRAINING_WINDOW // 5)
    samples_collected = {s: 0 for s in SERVICES}

    async with httpx.AsyncClient() as client:
        while True:
            start = time.perf_counter()

            for service_name, state in SERVICES.items():
                try:
                    raw = await fetch_metrics_for_service(client, service_name)
                    if raw is None:
                        continue

                    features = raw_to_features(raw)
                    state.add_sample(features)
                    state.last_raw  = raw
                    state.last_seen = datetime.now(timezone.utc).isoformat()
                    samples_collected[service_name] += 1

                    # Auto-train once we have enough warm-up data
                    if not state.trained and samples_collected[service_name] >= warmup_target:
                        log.info("[%s] Warm-up complete — training initial model", service_name)
                        state.train()

                    # Periodic retrain every TRAINING_WINDOW samples
                    if state.trained and samples_collected[service_name] % TRAINING_WINDOW == 0:
                        state.train()

                    score = state.predict(features)
                    state.last_score = score
                    prom_anomaly_score.labels(service=service_name).set(score)

                    event = {
                        "service":       service_name,
                        "anomaly_score": score,
                        "is_anomaly":    score >= ANOMALY_THRESHOLD,
                        "features":      raw,
                        "timestamp":     state.last_seen,
                    }
                    history.appendleft(event)

                    if score >= ANOMALY_THRESHOLD:
                        prom_anomaly_total.labels(service=service_name).inc()
                        log.warning(
                            "[%s] ANOMALY DETECTED score=%.3f error_rate=%.1f%% latency_p95=%.0fms",
                            service_name, score,
                            raw["error_rate_pct"], raw["latency_p95_ms"],
                        )
                        # Notify Healing Service
                        asyncio.create_task(
                            notify_healing_service(service_name, score, raw)
                        )

                except Exception as exc:
                    log.error("[%s] Poll error: %s", service_name, exc)

            elapsed = time.perf_counter() - start
            prom_prediction_latency.observe(elapsed)
            await asyncio.sleep(max(0, POLL_INTERVAL - elapsed))


async def notify_healing_service(service: str, score: float, raw: dict):
    """POST anomaly alert to the Healing Service so it can trigger circuit breaker."""
    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            await client.post(
                f"{HEALING_SERVICE_URL}/anomaly/alert",
                json={
                    "service":       service,
                    "anomaly_score": score,
                    "error_rate":    raw["error_rate_pct"],
                    "latency_p95":   raw["latency_p95_ms"],
                    "timestamp":     datetime.now(timezone.utc).isoformat(),
                },
            )
        log.info("[%s] Healing Service notified (score=%.2f)", service, score)
    except Exception as exc:
        log.warning("[%s] Could not reach Healing Service: %s", service, exc)


# ── App lifecycle ─────────────────────────────────────────────────────────────
@app.on_event("startup")
async def startup():
    asyncio.create_task(poll_loop())
    log.info("AI Predictor started — Swagger UI at http://localhost:8000/docs")


# ── Endpoints ─────────────────────────────────────────────────────────────────

@app.get("/health", response_model=HealthResponse, tags=["System"])
async def health():
    return {
        "status":   "ok",
        "uptime_s": int(time.time() - START_TIME),
        "services": {
            name: {
                "trained":     state.trained,
                "samples":     len(state.buffer),
                "last_score":  round(state.last_score, 3),
                "last_seen":   state.last_seen,
            }
            for name, state in SERVICES.items()
        },
    }


@app.get("/predict", response_model=list[PredictionResult], tags=["Prediction"])
async def predict_all(explain: bool = False):
    """Return the latest anomaly score for every monitored service."""
    results = []
    for name, state in SERVICES.items():
        llm = None
        if explain and state.last_score >= ANOMALY_THRESHOLD:
            llm = await llm_explain(state.last_raw, state.last_score)

        results.append(PredictionResult(
            service       = name,
            anomaly_score = round(state.last_score, 4),
            is_anomaly    = state.last_score >= ANOMALY_THRESHOLD,
            threshold     = ANOMALY_THRESHOLD,
            features      = state.last_raw,
            trained       = state.trained,
            timestamp     = state.last_seen or datetime.now(timezone.utc).isoformat(),
            recommendation= recommendation(state.last_score, state.last_raw),
            llm_analysis  = llm,
        ))
    return results


@app.post("/predict/{service_name}", response_model=PredictionResult, tags=["Prediction"])
async def predict_one(
    service_name: str,
    background_tasks: BackgroundTasks,
    explain: bool = False,
):
    """On-demand prediction for a specific service — fetches fresh metrics."""
    if service_name not in SERVICES:
        raise HTTPException(status_code=404, detail=f"Service '{service_name}' not monitored.")

    state = SERVICES[service_name]
    async with httpx.AsyncClient() as client:
        raw = await fetch_metrics_for_service(client, service_name)
    if raw is None:
        raise HTTPException(status_code=503, detail="Could not fetch metrics from Prometheus.")

    features = raw_to_features(raw)
    state.add_sample(features)
    if not state.trained and len(state.buffer) >= 20:
        state.train()

    score = state.predict(features)
    state.last_score = score
    state.last_raw   = raw

    llm = None
    if explain and score >= ANOMALY_THRESHOLD:
        llm = await llm_explain(raw, score)

    return PredictionResult(
        service       = service_name,
        anomaly_score = round(score, 4),
        is_anomaly    = score >= ANOMALY_THRESHOLD,
        threshold     = ANOMALY_THRESHOLD,
        features      = raw,
        trained       = state.trained,
        timestamp     = datetime.now(timezone.utc).isoformat(),
        recommendation= recommendation(score, raw),
        llm_analysis  = llm,
    )


@app.post("/train/{service_name}", response_model=TrainResponse, tags=["Model"])
async def retrain(service_name: str):
    """Manually trigger a model retrain on the current rolling buffer."""
    if service_name not in SERVICES:
        raise HTTPException(status_code=404, detail=f"Service '{service_name}' not monitored.")
    state = SERVICES[service_name]
    ok = state.train()
    return TrainResponse(
        service = service_name,
        success = ok,
        samples = len(state.buffer),
        message = f"Trained on {len(state.buffer)} samples." if ok else "Not enough data (need ≥ 20 samples).",
    )


@app.get("/history", tags=["Prediction"])
async def get_history(limit: int = 50, service: Optional[str] = None):
    """Return recent prediction history, newest first."""
    items = list(history)
    if service:
        items = [e for e in items if e["service"] == service]
    return items[:limit]


@app.get("/explain/{service_name}", tags=["LLM"])
async def explain(service_name: str):
    """Ask Ollama Llama 3 to explain the current anomaly (requires Ollama running)."""
    if service_name not in SERVICES:
        raise HTTPException(status_code=404, detail=f"Service '{service_name}' not monitored.")
    state = SERVICES[service_name]
    analysis = await llm_explain(state.last_raw, state.last_score)
    if analysis is None:
        raise HTTPException(
            status_code=503,
            detail="Ollama unavailable. Start it with: docker-compose up ollama && make ollama-pull"
        )
    return {"service": service_name, "analysis": analysis, "anomaly_score": state.last_score}


@app.get("/metrics", tags=["System"], include_in_schema=False)
async def metrics():
    """Prometheus scrape endpoint."""
    return Response(generate_latest(), media_type=CONTENT_TYPE_LATEST)
